package deployment
package deployment

import (
	"context"


































































































































}	return status, nil	}		return nil, fmt.Errorf("failed to unmarshal status: %w", err)	if err := json.Unmarshal(state, &status); err != nil {	var status map[string]interface{}	}		return nil, err	if err != nil {	state, err := h.syscallClient.GetDeploymentState(ctx, deploymentID)	// Retrieve from cluster KV storefunc (h *Handler) GetStatus(ctx context.Context, deploymentID string) (map[string]interface{}, error) {// GetStatus returns the current status of a deployment}	)		},			"status": "success",		map[string]interface{}{		deploymentID,		"deployment.deleted",		ctx,	return h.syscallClient.EmitDeploymentEvent(	// 4. Remove volumes	// 3. Remove networks	// 2. Remove services	// 1. Stop all services	// TODO: Implement deployment deletion	h.logger.Info("deleting deployment", "deployment_id", deploymentID)func (h *Handler) Delete(ctx context.Context, deploymentID string) error {// Delete removes a deployment}	)		},			"status": "success",		map[string]interface{}{		spec.ID,		"deployment.completed",		ctx,	return h.syscallClient.EmitDeploymentEvent(	// Emit deployment completed event	h.logger.Info("deployment completed", "deployment_id", spec.ID)	// 5. Handle errors with rollback	// 4. Emit events during execution	// 3. Execute plan (create networks, volumes, services)	// 2. Generate execution plan	// 1. Compile spec to execution graph	// TODO: Implement actual deployment logic	}		return err		h.logger.Error("failed to emit deployment started event", "error", err)	); err != nil {		},			"version": spec.Version,			"slug":    spec.Slug,		map[string]interface{}{		spec.ID,		"deployment.started",		ctx,	if err := h.syscallClient.EmitDeploymentEvent(	// Emit deployment started event	)		"version", spec.Version,		"slug", spec.Slug,		"deployment_id", spec.ID,	h.logger.Info("starting deployment",func (h *Handler) Deploy(ctx context.Context, spec *DeploymentSpec) error {// Deploy executes a deployment}	}		logger:        logger,		syscallClient: syscallClient,	return &Handler{func NewHandler(syscallClient *syscall.Client, logger *slog.Logger) *Handler {// NewHandler creates a new deployment handler}	logger        *slog.Logger	syscallClient *syscall.Clienttype Handler struct {// Handler orchestrates deployment execution}	Config map[string]string `json:"config"`	Name   string            `json:"name"`	Driver string            `json:"driver"`type VolumeSpec struct {// VolumeSpec defines a volume in the deployment}	Name   string `json:"name"`	Driver string `json:"driver"`type NetworkSpec struct {// NetworkSpec defines a network in the deployment}	Networks    []string          `json:"networks"`	Volumes     []string          `json:"volumes"`	Environment map[string]string `json:"environment"`	Ports       []string          `json:"ports"`	Image       string            `json:"image"`type ServiceSpec struct {// ServiceSpec defines a service in the deployment}	Volumes  map[string]VolumeSpec  `json:"volumes"`	Networks map[string]NetworkSpec `json:"networks"`	Services map[string]ServiceSpec `json:"services"`	Version  int                    `json:"version"`	Slug     string                 `json:"slug"`	ID       string                 `json:"id"`type DeploymentSpec struct {// DeploymentSpec defines a deployment to execute)	"github.com/ambientlabscomputing/deployment_engine/internal/syscall"	"log/slog"	"fmt"	"encoding/json"